package com.kestalkayden.hydrofarm.fluid;

import com.kestalkayden.hydrofarm.HydrofarmFabric;

import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.material.Fluid;

/** Mod-defined fluids. Currently just Liquid XP — generated by XP Drains, stored in liquid
 *  tanks, transferred via the pump/pipe network. Not placeable in the world (no source block,
 *  no bucket) for v1; exists purely as a fluid identity that the tank renderer can paint. */
public final class HydrofarmFluids {
    public static Fluid LIQUID_XP;
    public static Fluid FLUID_MILK;

    private HydrofarmFluids() {}

    public static void register() {
        LIQUID_XP = Registry.register(BuiltInRegistries.FLUID,
            Identifier.fromNamespaceAndPath(HydrofarmFabric.MOD_ID, "liquid_xp"),
            new LiquidXpFluid());

        FLUID_MILK = Registry.register(BuiltInRegistries.FLUID,
            Identifier.fromNamespaceAndPath(HydrofarmFabric.MOD_ID, "fluid_milk"),
            new FluidMilkFluid());
    }
}
